apiVersion: v1
kind: Service
metadata:
  name: overleaf-redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
    - port: 6379
  selector:
    app: overleaf-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overleaf-redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overleaf-redis
  template:
    metadata:
      labels:
        app: overleaf-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: overleaf-redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-redis-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
