apiVersion: v1
kind: Service
metadata:
  name: overleaf
  labels:
    app: overleaf
spec:
  type: {{ .Values.sharelatex.service.type }}
  ports:
    - port: {{ .Values.sharelatex.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: overleaf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overleaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overleaf
  template:
    metadata:
      labels:
        app: overleaf
    spec:
      containers:
        - name: sharelatex
          # Use default values so it doesn't crash if ArgoCD misses the values.yaml
          image: {{ default "sharelatex/sharelatex" .Values.sharelatex.image}}
          ports:
            - containerPort: 80
          env:
            - name: OVERLEAF_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: overleaf-site-url
                  key: site-url
            - name: OVERLEAF_EMAIL_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: overleaf-smtp-secret
                  key: smtp-pass
            - name: OVERLEAF_EMAIL_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: overleaf-smtp-user
                  key: smtp-user
            {{- range $key, $value := .Values.sharelatex.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: sharelatex-data
              mountPath: /var/lib/overleaf
      volumes:
        - name: sharelatex-data
          {{- if .Values.sharelatex.persistence.enabled }}
          persistentVolumeClaim:
            claimName: overleaf-sharelatex-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.sharelatex.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-sharelatex-pvc
spec:
  accessModes:
    - {{ .Values.sharelatex.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sharelatex.persistence.size }}
{{- end }}
